#!/usr/bin/env python3
"""扫描 reports/ 与 cases/ 的 frontmatter，校验 schema 并生成视图与导航。

生成物（首行均带 generated 哨兵，禁止手改）：
  index.md                  站点首页 = 活跃工作台
  views/active.md           活跃工作台（仓内浏览用，同首页）
  views/by-case.md          过程文档全景（含需求反链）
  views/all.md              全量索引
  cases/<case>/index.md     过程文档主页（阅读顺序）
  需求报告.md               全部档位需求总台账（按 tier 分组）
  SUMMARY.md                站点导航树（build_site.py 消费）
  assets/nav.js             顶部下拉导航数据（build_site.py 消费）

用法:
    python3 tools/build_views.py          # 校验 + 重新生成
    python3 tools/build_views.py --check  # 仅校验（含漂移检测），供钩子/CI
"""
import json
import posixpath
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("需要 pyyaml：pip install pyyaml", file=sys.stderr)
    raise

ROOT = Path(__file__).resolve().parent.parent
VIEWS = ROOT / "views"
MARK = "<!-- generated by tools/build_views.py — 禁止手改 -->"

TYPES = {"需求", "开发蓝图", "方案", "方案评审", "代码评审", "验收记录"}
TIERS = {"蓝图级", "标准级", "轻量级"}
REQUEST_STATUS = {"观察中", "待计划", "开发中", "已交付", "已作废"}
PLAN_STATUS = {"草拟中", "待评审", "需修改", "已通过", "已实施", "已归档"}
VERDICTS = {"通过", "需修改", "驳回"}
TERMINAL = {"已交付", "已作废", "已归档"}
REVIEW_TYPES = {"方案评审", "代码评审"}

# type → 必填附加字段
REQUIRED = {
    "需求": ["id", "status"],
    "开发蓝图": ["case", "status", "relates"],
    "方案": ["case", "phase", "version", "status", "relates"],
    "方案评审": ["case", "phase", "round", "verdict"],
    "代码评审": ["case", "phase", "round", "verdict"],
    "验收记录": ["case", "phase"],
}


def parse_frontmatter(path: Path):
    text = path.read_text(encoding="utf-8")
    if text.startswith("<!-- generated"):
        return None, None  # 生成文件，跳过
    if not text.startswith("---\n"):
        return None, f"{path.relative_to(ROOT)}: 缺少 frontmatter"
    end = text.find("\n---\n", 4)
    if end < 0:
        return None, f"{path.relative_to(ROOT)}: frontmatter 未闭合"
    try:
        meta = yaml.safe_load(text[4:end])
    except yaml.YAMLError as e:
        return None, f"{path.relative_to(ROOT)}: frontmatter 解析失败: {e}"
    if not isinstance(meta, dict):
        return None, f"{path.relative_to(ROOT)}: frontmatter 不是映射"
    meta["_path"] = path.relative_to(ROOT).as_posix()
    return meta, None


def collect():
    docs, errors = [], []
    for sub in ("reports", "cases"):
        for path in sorted((ROOT / sub).rglob("*.md")):
            meta, err = parse_frontmatter(path)
            if err:
                errors.append(err)
            elif meta:
                docs.append(meta)
    return docs, errors


def validate(docs):
    errors = []
    request_ids = {d.get("id") for d in docs if d.get("type") == "需求"}
    for d in docs:
        loc = d["_path"]
        for field in ("title", "type", "created"):
            if not d.get(field):
                errors.append(f"{loc}: 缺少必填字段 {field}")
        t = d.get("type")
        if t not in TYPES:
            errors.append(f"{loc}: type 非法: {t!r}")
            continue
        for field in REQUIRED[t]:
            if d.get(field) in (None, "", []):
                errors.append(f"{loc}: type={t} 缺少必填字段 {field}")
        status = d.get("status")
        if t == "需求" and status and status not in REQUEST_STATUS:
            errors.append(f"{loc}: 需求 status 非法: {status!r}")
        if t == "需求" and d.get("tier") and d["tier"] not in TIERS:
            errors.append(f"{loc}: tier 非法: {d['tier']!r}（枚举：蓝图级/标准级/轻量级）")
        if t in ("开发蓝图", "方案") and status and status not in PLAN_STATUS:
            errors.append(f"{loc}: {t} status 非法: {status!r}")
        if t in REVIEW_TYPES and d.get("verdict") not in VERDICTS:
            errors.append(f"{loc}: verdict 非法: {d.get('verdict')!r}")
        for rid in d.get("relates") or []:
            if rid not in request_ids:
                errors.append(f"{loc}: relates 指向不存在的需求 id: {rid!r}")
    return errors


def is_active(d):
    if d["type"] in REVIEW_TYPES or d["type"] == "验收记录":
        return False  # 评审/验收是事件记录，无活跃态
    return d.get("status") not in TERMINAL


def href(d, base):
    return posixpath.relpath(d["_path"], base or ".")


def link(d, base, label=None):
    return f"[{label or d['title']}]({href(d, base)})"


def short_label(d):
    """侧栏/过程文档主页用的短标签：去掉「<简称> 期N」前缀。"""
    parts = d["title"].split(" ", 2)
    return parts[2] if len(parts) == 3 and parts[1].startswith("期") else d["title"]


def doc_sort_key(d):
    type_order = {"开发蓝图": 0, "方案": 1, "方案评审": 2, "代码评审": 3, "验收记录": 4}
    return (
        str(d.get("phase") or ""),
        type_order.get(d["type"], 9),
        d.get("version") or d.get("round") or 0,
        d["_path"],
    )


def phase_groups(items):
    """一期之内按角色分组：当前方案 / 评审过程（按轮）/ 验收 / 历史版本。"""
    plans = sorted([d for d in items if d["type"] == "方案"],
                   key=lambda d: d.get("version") or 0)
    cur, olds = (plans[-1], plans[:-1]) if plans else (None, [])
    reviews = sorted([x for x in items if x["type"] in REVIEW_TYPES],
                     key=lambda d: (0 if d["type"] == "方案评审" else 1,
                                    d.get("round") or 0, d["_path"]))
    acc = [d for d in items if d["type"] == "验收记录"]
    return cur, reviews, acc, olds


def group_cases(docs):
    case_docs = [d for d in docs if d["type"] != "需求"]
    cases = {}
    for d in case_docs:
        cases.setdefault(d["case"], []).append(d)
    return cases


def render_active(docs, base):
    lines = [MARK, "# 活跃工作台", ""]
    active = [d for d in docs if is_active(d)]
    if not active:
        lines += ["当前无活跃文档。从 `templates/需求.md` 立第一个需求开始。", ""]
    by_case = {}
    for d in active:
        by_case.setdefault(d.get("case") or d.get("id") or "未分类", []).append(d)
    for case, items in sorted(by_case.items()):
        lines += [f"## {case}", "", "| 文档 | 类型 | 状态 |", "|---|---|---|"]
        for d in sorted(items, key=doc_sort_key):
            lines.append(f"| {link(d, base)} | {d['type']} | {d.get('status', '')} |")
        lines.append("")
    lines += ["---", "",
              "怎么读：过程文档主页（`cases/<case>/index.md`）给出阅读顺序；"
              "全景与索引见左侧「工作台」。"]
    return "\n".join(lines) + "\n"


def render_by_case(docs, base):
    lines = [MARK, "# 过程文档全景", ""]
    requests = [d for d in docs if d["type"] == "需求"]
    cases = group_cases(docs)
    if not cases:
        lines += ["当前无过程文档。", ""]
    for case, items in sorted(cases.items()):
        items = sorted(items, key=doc_sort_key)
        lines += [f"## {case}", ""]
        related_ids = {rid for d in items for rid in d.get("relates") or []}
        rel = [r for r in requests if r["id"] in related_ids]
        if rel:
            lines.append("**关联需求**: " + "、".join(
                f"{link(r, base)}（{r.get('status', '')}）" for r in rel))
            lines.append("")
        lines += ["| 文档 | 类型 | 期 | 状态/结论 | 创建 |", "|---|---|---|---|---|"]
        for d in items:
            state = d.get("status") or d.get("verdict") or ""
            lines.append(
                f"| {link(d, base)} | {d['type']} | {d.get('phase', '')} | {state} | {d.get('created', '')} |")
        lines.append("")
    used = {rid for c in cases.values() for d in c for rid in d.get("relates") or []}
    orphan = [r for r in requests if r["id"] not in used]
    if orphan:
        lines += ["## 未挂案需求", "", "| 需求 | 状态 |", "|---|---|"]
        for r in sorted(orphan, key=lambda d: d.get("id", "")):
            lines.append(f"| {link(r, base)} | {r.get('status', '')} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_all(docs, base):
    lines = [MARK, "# 全量索引", "",
             "| 文档 | 类型 | 过程文档 | 状态/结论 | 创建 |", "|---|---|---|---|---|"]
    if not docs:
        lines += ["| — | — | — | — | — |"]
    for d in sorted(docs, key=lambda d: (str(d.get("created", "")), d["_path"])):
        state = d.get("status") or d.get("verdict") or ""
        lines.append(
            f"| {link(d, base)} | {d['type']} | {d.get('case', d.get('id', ''))} | {state} | {d.get('created', '')} |")
    return "\n".join(lines) + "\n"


def render_report(docs, cases, base=""):
    """需求报告：全部档位的需求总台账（蓝图级/标准级/轻量级/未定档），含关联过程文档反链。"""
    requests = [d for d in docs if d["type"] == "需求"]
    rel_cases = {}
    for case, items in cases.items():
        for d in items:
            for rid in d.get("relates") or []:
                rel_cases.setdefault(rid, set()).add(case)
    counts = {}
    for r in requests:
        counts[r.get("tier") or "未定档"] = counts.get(r.get("tier") or "未定档", 0) + 1
    head = " · ".join(f"{t} {counts[t]}" for t in ("蓝图级", "标准级", "轻量级", "未定档")
                      if t in counts) or "暂无需求"
    lines = [MARK, "# 需求报告", "", "共 " + str(len(requests)) + " 项：" + head, ""]
    for tier in ("蓝图级", "标准级", "轻量级", "未定档"):
        group = [r for r in requests if (r.get("tier") or "未定档") == tier]
        if not group:
            continue
        lines += [f"## {tier}", "", "| 需求 | 状态 | 关联过程文档 | 创建 |", "|---|---|---|---|"]
        for r in sorted(group, key=lambda d: (str(d.get("created", "")), d.get("id", ""))):
            cs = "、".join(sorted(rel_cases.get(r["id"], []))) or "—"
            lines.append(f"| {link(r, base)} | {r.get('status', '')} | {cs} | {r.get('created', '')} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_case_index(case, items, requests, base):
    lines = [MARK, f"# {case}", ""]
    related_ids = {rid for d in items for rid in d.get("relates") or []}
    rel = [r for r in requests if r["id"] in related_ids]
    if rel:
        lines.append("**关联需求**: " + "、".join(
            f"{link(r, base)}（{r.get('status', '')}）" for r in rel))
        lines.append("")
    bps = [d for d in items if d["type"] == "开发蓝图"]
    for bp in bps:
        lines.append(f"**蓝图**: {link(bp, base)}（{bp.get('status', '')}）")
        lines.append("")
    phases = {}
    for d in items:
        if d["type"] != "开发蓝图":
            phases.setdefault(d.get("phase"), []).append(d)
    for phase in sorted(phases, key=str):
        cur, reviews, acc, olds = phase_groups(phases[phase])
        lines += [f"## 期{phase}", ""]
        if cur:
            lines += [f"**当前方案**：{link(cur, base, short_label(cur))}"
                      f"——{cur.get('status', '')}", ""]
        if reviews:
            lines += ["**评审过程**（按轮次读）", ""]
            for i, d in enumerate(reviews, 1):
                lines.append(f"{i}. {link(d, base, short_label(d))}——{d.get('verdict', '')}")
            lines.append("")
        for d in acc:
            lines += [f"**验收**：{link(d, base, short_label(d))}", ""]
        if olds:
            lines += ["**历史版本**（仅考古）：" + "、".join(
                link(d, base, short_label(d)) for d in olds), ""]
    lines += ["---", "",
              "阅读协议：先读当前方案，再按轮读评审，最后验收；历史版本仅考古；"
              "判断现状只看 frontmatter 的 status/verdict。"]
    return "\n".join(lines) + "\n"


def nav_model(docs, cases):
    """统一导航模型：SUMMARY.md（侧栏）与 assets/nav.js（顶部下拉）共用。
    固定四个顶层分区（工作台/需求/过程文档/规范），期内按 当前方案/评审过程/验收/历史版本 分组。"""
    def page(label, path):
        return {"label": label, "path": path}

    def sec(label, children):
        return {"label": label, "children": children}

    model = [sec("工作台", [page("活跃工作台", "index.md"),
                            page("过程文档全景", "views/by-case.md"),
                            page("全量索引", "views/all.md"),
                            page("需求报告", "需求报告.md")])]
    requests = sorted([d for d in docs if d["type"] == "需求"],
                      key=lambda d: d.get("id", ""))
    if requests:
        model.append(sec("需求", [page(r["title"], r["_path"]) for r in requests]))
    case_nodes = []
    for case, items in sorted(cases.items()):
        children = [page("主页", f"cases/{case}/index.md")]
        children += [page("蓝图", bp["_path"])
                     for bp in items if bp["type"] == "开发蓝图"]
        phases = {}
        for d in items:
            if d["type"] != "开发蓝图":
                phases.setdefault(d.get("phase"), []).append(d)
        for phase in sorted(phases, key=str):
            cur, reviews, acc, olds = phase_groups(phases[phase])
            pchildren = []
            if cur:
                pchildren.append(page(f"{short_label(cur)}（当前）", cur["_path"]))
            if reviews:
                pchildren.append(sec("评审过程",
                                     [page(short_label(d), d["_path"]) for d in reviews]))
            pchildren += [page(short_label(d), d["_path"]) for d in acc]
            if olds:
                pchildren.append(sec("历史版本",
                                     [page(short_label(d), d["_path"]) for d in olds]))
            children.append(sec(f"期{phase}", pchildren))
        case_nodes.append(sec(case, children))
    if case_nodes:
        model.append(sec("过程文档", case_nodes))
    model.append(sec("规范", [page("规范主页", "规范.md"),
                              page("职责与角色", "规范/职责与角色.md"),
                              page("三档分级与分期模式", "规范/三档分级与分期模式.md"),
                              page("方案要件与检查清单", "规范/方案要件与检查清单.md"),
                              page("流程、自检与 Gate", "规范/流程、自检与Gate.md"),
                              page("评审规则", "规范/评审规则.md"),
                              page("实施纪律与终扫", "规范/实施纪律与终扫.md"),
                              page("本仓操作规范", "规范/本仓操作规范.md"),
                              page("Schema", "SCHEMA.md")]))
    return model


def render_summary(model):
    lines = [MARK]

    def emit(nodes, depth):
        for n in nodes:
            ind = "    " * depth
            if "path" in n:
                lines.append(f"{ind}- [{n['label']}]({n['path']})")
            else:
                lines.append(f"{ind}- {n['label']}")
                emit(n["children"], depth + 1)

    emit(model, 0)
    return "\n".join(lines) + "\n"


def render_nav_js(model):
    return ("// generated by tools/build_views.py — 禁止手改\n"
            "window.WB_NAV = " + json.dumps(model, ensure_ascii=False) + ";\n")


def main():
    check = "--check" in sys.argv
    docs, errors = collect()
    errors += validate(docs)
    if errors:
        print("校验失败：", file=sys.stderr)
        for e in errors:
            print(f"  ✗ {e}", file=sys.stderr)
        return 1

    requests = [d for d in docs if d["type"] == "需求"]
    cases = group_cases(docs)
    model = nav_model(docs, cases)
    outputs = {
        VIEWS / "active.md": render_active(docs, "views"),
        VIEWS / "by-case.md": render_by_case(docs, "views"),
        VIEWS / "all.md": render_all(docs, "views"),
        ROOT / "index.md": render_active(docs, ""),
        ROOT / "需求报告.md": render_report(docs, cases),
        ROOT / "SUMMARY.md": render_summary(model),
        ROOT / "assets" / "nav.js": render_nav_js(model),
    }
    for case, items in cases.items():
        outputs[ROOT / "cases" / case / "index.md"] = render_case_index(
            case, items, requests, f"cases/{case}")

    VIEWS.mkdir(exist_ok=True)
    drift = []
    for target, content in outputs.items():
        name = target.relative_to(ROOT).as_posix()
        old = target.read_text(encoding="utf-8") if target.exists() else ""
        if old != content:
            if check:
                drift.append(name)
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
                print(f"  ✓ 重新生成 {name}")
    if check and drift:
        print(f"视图漂移（需重跑 build_views.py）: {', '.join(drift)}", file=sys.stderr)
        return 1
    print(f"OK: {len(docs)} 篇文档，校验通过" + ("" if check else "，视图已更新"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
